# Backend Dockerfile

FROM python:3.11-slim

WORKDIR /app

# Add dependencies here
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# COPY . .

# CMD ["python", "-m", "uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
